FROM eclipse-temurin:21-jre-alpine

RUN apk add --no-cache tesseract-ocr ghostscript

WORKDIR /app
COPY target/SWEN3_DMS-1.0-SNAPSHOT.jar app.jar

ENTRYPOINT ["java", "-Dspring.profiles.active=ocr", "-Dloader.main=com.swen3.paperless.worker.ocr.OcrWorkerApp", "-cp", "app.jar", "org.springframework.boot.loader.launch.PropertiesLauncher"]
