FROM eclipse-temurin:21-jre

WORKDIR /app
COPY target/SWEN3_DMS-1.0-SNAPSHOT.jar app.jar

ENTRYPOINT ["java", "-Dspring.profiles.active=genai", "-Dloader.main=com.swen3.paperless.worker.genai.GenAiWorkerApp", "-cp", "app.jar", "org.springframework.boot.loader.launch.PropertiesLauncher"]
